services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    image: lilnikky/itmo_practice_frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    image: lilnikky/itmo_practice_backend
